### ISSUE TITLE
Empty compile_commands.json 

### ISSUE THREAD

**Issue by hemantabhagat** [rprichard/sourceweb#11]
Hi,

I have built an only 

> btrace

 library and tried testing it with some project. What happens is btrace.log file is generated but when I try to create compile_commands.json with command `sw-btrace-to-compiledb` an empty compile_commands.json file is created. Am I missing something?
PFA btrace.log file

[btrace.zip](https://github.com/rprichard/sourceweb/files/1102534/btrace.zip)

**Comment by rprichard** [comment]
I don't see any compile commands in the btrace.log.  e.g. `sw-btrace-to-compiledb` is looking for invocations of `gcc`, `g++`, `clang`, etc.  Are you using a special compiler?  Did you prefix `sw-btrace` to the command that builds your project?

**Comment by hemantabhagat** [comment]
Yes, I did.

I am building my project with make. It build successfully.
I ran like this

$ /home/Downloads/sourceweb-master/btrace/sw-btrace make

Thanks,
Hemant

**Comment by hemantabhagat** [comment]
Also, I am using g++ compiler. I don’t have CC or C++ environment variable set. Does it have dependency on environment variables?

Thanks,
Hemant

**Comment by rprichard** [comment]
Maybe you need to clean your build first?

sw-btrace is a simple `LD_PRELOAD` library that writes its argv to `btrace.log`.  You can see how it works with the demo included in SourceWeb.  It should be writing command like `gcc -c <file.c> -o <file.o>` to the `btrace.log` file, but they're not there.  That's why `sw-btrace-to-compiledb` is outputting an empty `compile_commands.json` file.

**Comment by rprichard** [comment]
> Also, I am using g++ compiler. I don’t have CC or C++ environment variable set. Does it have dependency on environment variables?

No.  Neither `sw-btrace` nor `sw-btrace-to-compiledb` cares about environment variables like `CC`, `CXX`, `CPP`, etc.

**Comment by hemantabhagat** [comment]
Yes, you are right. I just clean my build directory and it worked perfectly.
I must have done it earlier.
Thank you very much for your time.

BTW what are your thoughts on making it work for windows?

Thanks,
Hemant

**Comment by rprichard** [comment]
I'm open to someone making it work on Windows, then sending me patches.

Someone else tried to make it work on Windows and had some degree of success, eventually.  They had to fix a few things.  If I recall correctly, the biggest single bug was that files needed to be opened with a "binary" flag to prevent CRLF<->LF conversions.

**Comment by hemantabhagat** [comment]
Sure Richards,

I will definitely try out the feasibility on windows then discuss with you.
Thanks again for your time. Have a great day! 😊

-Hemant

**Comment by hemantabhagat** [comment]
Hi Richard,

I am trying to use btrace with scons build system. And I cleaned the build system.
When I build the attached project, I can see the compiler invocations printed on the console but not logged in btrace.log file. And hence compile_commands.json is empty.

Does btrace work with scons?

Also, I compiled the above project with intercept-build from clang also just to cross check and it worked as expected.

-Hemant

**Comment by rprichard** [comment]
AFAIK, btrace should work just as well with SCons as it does with CMake, make, or any other build tool.

If SCons runs a command, but btrace doesn't log it, then one of several things may have happened:
 - The compiler is 32-bit, but you only have a 64-bit `libsw-btrace.so` on your `LD_PRELOAD` variable.  (Or vice versa.)  I have a hacked-up version of sw-btrace that provides both x86 and x86_64 preload libraries, but I haven't seriously looked at fixing the build system to build both architecture variants.
 - The compiler is statically linked.  This is unlikely on Linux.
 - The build tool is clearing the `LD_PRELOAD` variable.

It looks like `intercept-build` uses the same `LD_PRELOAD` mechanism as `sw-btrace` to log commands, so if `intercept-build` works, then `sw-btrace` should also work.  SourceWeb doesn't care how you come up with a compilation database, so if `intercept-build` works for you, that's also fine.
