### ISSUE TITLE
<< llvm::StringRef » in « const char*

### ISSUE THREAD

**Issue by gerisse** [rprichard/sourceweb#19]
when i compiled with 'sudo make install' (archlinux 64 bits), i had this issue : 
../../clang-indexer/IndexerContext.cc: Dans la fonction membre « indexer::IndexerFileContext& indexer::IndexerContext::fileContext(clang::FileID) »:
../../clang-indexer/IndexerContext.cc:162:61: error: ne peut convertir « llvm::StringRef » en « const char* » pour l'argument « 1 » de « char* indexer::portableRealPath(const char*) »
             char *filename = portableRealPath(pFE->getName());
an idea ?
thanks

**Comment by rprichard** [comment]
I would guess that you're using the wrong version of Clang to compile SourceWeb. SourceWeb requires an exact version of Clang. Until today, it required Clang 3.8, but I just merged a commit a minute ago porting the version to Clang 4.0.

Specifically, I merged this 3.8->4.0 commit: https://github.com/rprichard/sourceweb/commit/d5f86381b1aad7a0891b89e7eb9a338ce9038796

You can see that the `FileEntry::getName()` used to be passed directly to `portableRealPath`, but now it's assigned to an `llvm::StringRef` and `llvm::StringRef::data()` is used to get a char pointer.

If you pull this change, it might fix your problem.

**Comment by gerisse** [comment]
yes, it's the solution : it's ok . thanks
